version: "3.9"
services:
  mysql:
    image: "mysql/mysql-server:8.0.20"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_ROOT_HOST: "%"

  redis:
    image: redis
    ports:
      - 6379:6379

