info:
  component: 'MagicTG'
  build:
    version: "1.0.0"
    name: "MTG"

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: mtg
  autoconfigure:
    exclude:
      #- org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/magic
    username: root
    password: 12345

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://myProdServer:3306/magic
    username: root
    password: 12345
#    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

## application .yml

#batata:
#  cebola: 2
#  config:
#    frita: True
#
## application .properties

#batata.cebola=2
#batata.config.frita=True


## Onde esse bloco de código entra? Onde ele faz sentido?
#  spring.datasource.url=jdbc:h2:mem:testdb
#  spring.datasource.driverClassName=org.h2.Driver
#  spring.datasource.username=sa
#  spring.datasource.password=
#  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
#  # temporary data storage
#  spring.datasource.url = jdbc:h2:mem:testdb
#
#  # temporary data storage
#  spring.datasource.url = jdbc:h2:file:/data/sample
#  spring.datasource.url = jdbc:h2:file:C:/data/sample #(Windows only)



